module.exports = {
  User: require('./User'),
  Role: require('./Role'),
  Setting: require('./Setting'),
  Berth: require('./Berth'),
  Lookup: require('./Lookup'),
  TariffItem: require('./TariffItem'),
  ChecklistTemplate: require('./ChecklistTemplate'),
  Vessel: require('./Vessel'),
  PortCall: require('./PortCall'),
  Inspection: require('./Inspection'),
  Invoice: require('./Invoice'),
  AuditLog: require('./AuditLog'),
  Notification: require('./Notification'),
  Seafarer: require('./Seafarer'),
  Instrument: require('./Instrument'),
  License: require('./License'),
  Incident: require('./Incident'),
  MdaAlert: require('./MdaAlert'),
  Position: require('./Position'),
  Resource: require('./Resource'),
  Company: require('./Company'),
  VesselRegistration: require('./VesselRegistration'),
  ServiceDefinition: require('./ServiceDefinition'),
  ServiceRequest: require('./ServiceRequest'),
  AgentConfig: require('./AgentConfig'),
  AiDecision: require('./AiDecision'),
};
