import React from "react";
import { PageHeader, Card } from "../components/ui.jsx";
import { useLang } from "../lib/i18n.jsx";

export default function Methodology() {
  const { t } = useLang();
  const pStyle = { fontSize: 13.5, color: "var(--muted)", lineHeight: 1.6 };
  return (
    <>
      <PageHeader
        title="Data & methodology"
        sub="What powers Sagar Drishti, how the numbers are sourced, and the limits of the current build."
      />
      <div className="grid two">
        <Card title="Primary data">
          <p style={pStyle}>
            {t("The Mundra Port operations snapshot (Jan 2023 → today, deterministic demo world): 31 vessels, ~1,200 port calls, HSE incidents, PSC/flag-state inspections, invoices and seafarer records across 24 berths, 10 terminals and 3 zones. The records are aggregated into four monthly panels — ops, marine, hse and revenue — at port → zone → terminal → berth grain. Berth is the finest grain; role-based scoping controls what each user sees. All transactions are fictional; the 8 documented liner callers never appear on watchlists.")}
          </p>
        </Card>
        <Card title="Ground-truth & benchmarks">
          <p style={pStyle}>
            {t("Public Indian major-port statistics are the yardstick: ~50.4h average turnaround, a 5h pre-berthing norm, the 40–70% healthy occupancy band, berth-day output targets, the Indian Ocean MoU PSC detention benchmark (~5.6%) and a 95% collection target. Composite terminal risk blends incident rate (35%), waiting (25%), high-severity incidents (25%) and detentions (15%) over the trailing 12 months.")}
          </p>
        </Card>
      </div>

      <div style={{ marginTop: 16 }}>
        <Card title="How the analysis works">
          <ul style={{ fontSize: 13.5, color: "var(--muted)", lineHeight: 1.7, paddingLeft: 18, margin: 0 }}>
            <li>{t("Operations audit — anchorage-queue concentrations, turnaround vs traffic, berth-on-arrival service, incident patterns and receivables exposure, flagged automatically with evidence.")}</li>
            <li>{t("Benchmark vs major ports — turnaround, waiting, occupancy, detentions and collection per unit against the public major-port yardsticks.")}</li>
            <li>{t("Terminal hotspots — the vessel types and units that most need marine-services effort.")}</li>
            <li>{t("Early warning — the anchorage-waiting trend and a next-month projection (linear fit).")}</li>
            <li>{t("3D terminal twin — the composite terminal risk score rendered over the Mundra estate's own geometry (11 terminal polygons, two offshore SPM pads), extruded and coloured per metric.")}</li>
            <li>{t("Agent workforce — six agents run every 2 hours: the Harbour Collector rebuilds the panels, the Berth Sentinel flags waiting-time shifts per terminal, the Marine Auditor scores service, the Berth Planner drafts actions, and the Trade Analyst writes the cycle brief under the Duty Officer's orchestration.")}</li>
            <li>{t("Sagar Intelligence assistant — answers from the panels instantly (scoped to your access); free-form questions and full formatted reports are generated by the LLM over the live data, with copy / email / PDF export.")}</li>
          </ul>
        </Card>
      </div>

      <div style={{ marginTop: 16 }}>
        <Card title="Two personas, one platform">
          <p style={{ fontSize: 13.5, lineHeight: 1.6 }}>
            {t("The port authority sees the whole-port view — traffic, service levels, safety and money across every terminal. A terminal operator sees the operational view for their own terminal and berths. Both read the same data, filtered to each user's scope and framed for their role.")}
          </p>
        </Card>
      </div>

      <div style={{ marginTop: 16 }}>
        <Card title="Caveats & roadmap">
          <p style={pStyle}>
            {t("This is a deterministic demo world built from public benchmark statistics — figures are internally consistent but fictional. P&I claims and off-port casualty history live outside the portal; beneficial-ownership chains are not recorded (agent and operator are the working contacts). Roadmap: live AIS and VTMS feeds, the port document library for RAG, tide/UKC-aware berth-window planning, and templating the connector to the other APSEZ ports.")}
          </p>
        </Card>
      </div>
    </>
  );
}
