"""Central configuration for the Sagar Drishti (Mundra Port AI Analytics) backend."""
import os

# Resolve project root: portal/backend/app/config.py -> up 3 = project root
_HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(_HERE, "..", "..", ".."))

# Mundra panels + analysis artifacts (generated by data/mundra/build_panels.py
# and analysis/analyze_mundra.py from the portal's demo snapshot)
DATA_DIR = os.path.join(PROJECT_ROOT, "data", "mundra", "portal", "processed")
ANALYSIS_DIR = os.path.join(PROJECT_ROOT, "analysis", "out_mundra")
GEO_DIR = os.path.join(PROJECT_ROOT, "data", "geo_mundra")

# The builder scripts (for the scheduled refresh cycle)
BUILDER_DIR = os.path.join(PROJECT_ROOT, "data", "mundra")

# Auth (env override kept; SAGAR_* preferred, HTM_* still honored for continuity)
JWT_SECRET = os.environ.get("SAGAR_JWT_SECRET", os.environ.get("HTM_JWT_SECRET",
                            "sagar-drishti-dev-secret-change-in-prod"))
JWT_ALGO = "HS256"
TOKEN_TTL_HOURS = 12

# LLM chatbot. Priority: local Claude CLI (OAuth), then Anthropic API if key set.
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
LLM_MODEL = os.environ.get("SAGAR_LLM_MODEL", "claude-sonnet-4-5")

CLAUDE_BINARY = os.environ.get("SAGAR_CLAUDE_BINARY", os.environ.get("HTM_CLAUDE_BINARY", "claude"))
CLAUDE_MODEL = os.environ.get("SAGAR_CLAUDE_MODEL", os.environ.get("HTM_CLAUDE_MODEL", "opus"))
CLAUDE_TIMEOUT_S = int(os.environ.get("SAGAR_CLAUDE_TIMEOUT", "180"))
CLAUDE_EXTRA_ARGS = os.environ.get("SAGAR_CLAUDE_EXTRA_ARGS", "")
CLAUDE_HOME = os.environ.get("SAGAR_CLAUDE_HOME", "")

# Agent workforce — default to a 2-hourly enrichment cycle
AGENT_MODEL = os.environ.get("SAGAR_AGENT_MODEL", "sonnet")
AGENT_STATE_DIR = os.path.join(_HERE, "..", "agent_state")
AGENT_SCHEDULE_HOUR = int(os.environ.get("SAGAR_AGENT_SCHEDULE_HOUR", "7"))
AGENT_SCHEDULE_INTERVAL = int(os.environ.get("SAGAR_AGENT_INTERVAL_HOURS", "2"))
AGENT_SCHEDULE_ENABLED = os.environ.get("SAGAR_AGENT_SCHEDULE", "1") != "0"

# CORS origins for the Vite dev server
CORS_ORIGINS = [
    "http://localhost:5273", "http://127.0.0.1:5273",
    "http://localhost:5173", "http://127.0.0.1:5173",
    "http://localhost:4173", "http://127.0.0.1:4173",
]
