"""
Data layer — loads the Mundra panels (ops / marine / hse / revenue) at
port → zone → terminal → berth grain, plus the findings feed and the
major-port benchmark, once at startup. Exposes pandas frames, an in-memory
SQLite mirror (analytics + chatbot text-to-SQL), scope-aware RBAC filtering,
and a reload() used by the scheduled agent refresh.

Source of truth is the Mundra portal's deterministic demo snapshot; the CSVs
are regenerated by data/mundra/build_panels.py + analysis/analyze_mundra.py.
"""
import json
import math
import os
import sqlite3
import threading

import pandas as pd

from . import config

# Mundra panels loaded from DATA_DIR
_PANELS = ["ops", "marine", "hse", "revenue"]

# unit-hierarchy invariant present in every panel
_UNIT_COLS = ["level", "unit_id", "unit_name", "zone", "terminal", "ym"]


def _cl(v):
    """JSON-safe scalar (NaN/Inf -> None, numpy -> python)."""
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return None
    try:
        import numpy as _np
        if isinstance(v, _np.generic):
            return v.item()
    except Exception:
        pass
    return v


class Store:
    def __init__(self):
        self._sql_lock = threading.Lock()
        self.conn = None
        self._load()

    # ---------------------------------------------------------------- load
    def _load(self):
        self.frames = {}
        for p in _PANELS:
            fp = os.path.join(config.DATA_DIR, f"{p}.csv")
            if os.path.exists(fp):
                df = pd.read_csv(fp, dtype={"zone": str, "terminal": str})
                for col in ("zone", "terminal"):
                    if col in df.columns:
                        df[col] = df[col].fillna("")
                self.frames[p] = df

        # findings
        self.findings, self.meta = [], {}
        fj = os.path.join(config.ANALYSIS_DIR, "findings.json")
        if os.path.exists(fj):
            doc = json.load(open(fj))
            self.findings = doc.get("findings", [])
            self.meta = doc.get("meta", {})

        # major-port benchmark (public-statistics yardstick)
        self.benchmark = {}
        bf = os.path.join(config.ANALYSIS_DIR, "benchmark.csv")
        if os.path.exists(bf):
            self.benchmark = pd.read_csv(bf).iloc[0].to_dict()

        # vessel reliability + rankings (analysis tables)
        for t in ["vessel_reliability", "unit_latest", "hotspot_ranking",
                  "vessel_watchlist", "terminal_trends"]:
            fp = os.path.join(config.ANALYSIS_DIR, f"{t}.csv")
            if os.path.exists(fp):
                self.frames[t] = pd.read_csv(fp)

        self.region = None
        rj = os.path.join(config.ANALYSIS_DIR, "regionwise.json")
        if os.path.exists(rj):
            try:
                self.region = json.load(open(rj))
            except Exception:
                self.region = None

        # deep-analysis sections pack (fleet/incidents/inspections/revenue/crew)
        self.sections = {}
        sj = os.path.join(config.ANALYSIS_DIR, "sections.json")
        if os.path.exists(sj):
            try:
                self.sections = json.load(open(sj))
            except Exception:
                self.sections = {}

        # latest COMPLETE month — authoritative from the pipeline's meta.json (the
        # in-progress calendar month is partial and must not headline KPIs).
        self.latest_month = None
        mj = os.path.join(config.ANALYSIS_DIR, "meta.json")
        if os.path.exists(mj):
            try:
                pmeta = json.load(open(mj))
                self.meta = {**pmeta, **self.meta}
                self.latest_month = pmeta.get("latest_month")
            except Exception:
                pass
        self.latest_month = self.latest_month or self.meta.get("latest_month")
        if not self.latest_month and "ops" in self.frames:
            import datetime as _dt
            cur = _dt.date.today().strftime("%Y-%m")
            months = sorted(self.frames["ops"]["ym"].astype(str).unique())
            done = [m for m in months if m < cur]
            self.latest_month = done[-1] if done else (months[-1] if months else None)

        # data-version stamp — the newest mtime across the pipeline's outputs. It
        # changes whenever the Harbour Collector rebuilds, so cached AI narratives
        # (section / record / explain) invalidate and regenerate against fresh data.
        stamps = []
        for f in ("meta.json", "findings.json", "sections.json", "regionwise.json"):
            fp = os.path.join(config.ANALYSIS_DIR, f)
            if os.path.exists(fp):
                try:
                    stamps.append(os.path.getmtime(fp))
                except OSError:
                    pass
        self.data_version = str(int(max(stamps))) if stamps else "0"

        self._build_latest()
        self._build_sqlite()

    def reload(self):
        """Rebuild everything from disk (called by the scheduled Harbour Collector
        after the panel builder refreshes the CSVs). Thread-safe swap."""
        with self._sql_lock:
            if self.conn is not None:
                try:
                    self.conn.close()
                except Exception:
                    pass
            self._load()
        return {"latest_month": self.latest_month,
                "panels": list(self.frames.keys()),
                "units": int(len(self.unit_latest))}

    def _build_latest(self):
        """Wide latest-month snapshot per unit (all levels), merging all panels."""
        ops = self.frames.get("ops")
        lm = self.latest_month
        base = ops[ops.ym == lm].copy() if ops is not None else pd.DataFrame(columns=_UNIT_COLS)

        def latest(panel, cols):
            df = self.frames.get(panel)
            if df is None:
                return None
            if "ym" in df.columns:
                yms = set(df.ym.astype(str))
                lm2 = lm if str(lm) in yms else df.ym.max()  # align to last complete month
                d = df[df.ym.astype(str) == str(lm2)]
            else:
                d = df
            keep = [c for c in cols if c in d.columns]
            return d[["unit_id"] + keep] if keep else None

        for panel, cols in (
            ("marine", ["pilotage_moves", "tug_jobs", "inspections_done",
                        "findings_raised", "findings_closed", "detentions"]),
            ("hse", ["incidents_total", "incidents_high_critical", "injuries",
                     "spills", "near_miss", "avg_close_days"]),
            ("revenue", ["invoices_issued", "billed_cr", "collected_cr",
                         "outstanding_cr", "collection_pct"]),
        ):
            m = latest(panel, cols)
            if m is not None:
                base = base.merge(m, on="unit_id", how="left", suffixes=("", f"_{panel}"))

        for c in ("incidents_total", "incidents_high_critical", "injuries",
                  "detentions", "outstanding_cr"):
            if c in base.columns:
                base[c] = base[c].fillna(0)
        self.unit_latest = base.drop_duplicates("unit_id").reset_index(drop=True)
        # back-compat alias for terminal-level consumers
        self.terminal_latest = base[base.level == "terminal"].copy()

    def _build_sqlite(self):
        self.conn = sqlite3.connect(":memory:", check_same_thread=False)
        for name, df in self.frames.items():
            try:
                df.to_sql(name, self.conn, if_exists="replace", index=False)
            except Exception:
                pass
        try:
            self.unit_latest.to_sql("unit_latest", self.conn, if_exists="replace", index=False)
        except Exception:
            pass

    # ---------------------------------------------------------------- RBAC
    @staticmethod
    def scope_of(user):
        return (user or {}).get("scope", "port") or "port"

    def visible(self, df, user):
        """Filter any panel/frame to the units this user's scope may see."""
        if df is None or not len(df):
            return df
        scope = self.scope_of(user)
        if scope in ("port", "state"):
            return df
        if ":" not in scope:
            return df
        kind, key = scope.split(":", 1)
        if kind == "zone" and "zone" in df.columns:
            return df[df.zone == key]
        if kind == "terminal" and "terminal" in df.columns:
            return df[df.terminal == key]
        if kind == "berth" and "unit_id" in df.columns:
            return df[df.unit_id == key]
        return df

    def home_unit_id(self, user):
        """The unit_id of the user's own aggregate level (their headline row)."""
        scope = self.scope_of(user)
        if scope in ("port", "state") or ":" not in scope:
            return "INMUN"
        kind, key = scope.split(":", 1)
        row = self.unit_latest[(self.unit_latest.level == kind) &
                               ((self.unit_latest.unit_name == key) | (self.unit_latest.unit_id == key))]
        if len(row):
            return row.iloc[0].unit_id
        return "INMUN"

    def child_level(self, user):
        """The level a user drills into (port->zone, zone->terminal, terminal->berth)."""
        scope = self.scope_of(user)
        return {"port": "zone", "state": "zone", "zone": "terminal",
                "terminal": "berth", "berth": "berth"}.get(scope.split(":", 1)[0], "terminal")

    # ---------------------------------------------------------------- SQL
    def sql(self, query, limit=200):
        q = query.strip().rstrip(";")
        low = q.lower()
        if not low.startswith("select") and not low.startswith("with"):
            raise ValueError("Only SELECT queries are permitted.")
        forbidden = ["insert", "update", "delete", "drop", "alter", "create",
                     "attach", "pragma", "replace ", " into "]
        if any(f in low for f in forbidden):
            raise ValueError("Query contains a forbidden keyword.")
        if " limit " not in low:
            q += f" LIMIT {limit}"
        with self._sql_lock:
            cur = self.conn.execute(q)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]
        return {"columns": cols, "rows": rows}

    def schema_text(self):
        lines = []
        for name in ["unit_latest", "ops", "marine", "hse", "revenue", "vessel_reliability"]:
            try:
                cur = self.conn.execute(f"PRAGMA table_info({name})")
                cols = [r[1] for r in cur.fetchall()]
                if cols:
                    lines.append(f"{name}({', '.join(cols)})")
            except Exception:
                pass
        return "\n".join(lines)

    # ---------------------------------------------------------------- LLM context
    def context_pack(self, user=None):
        """Compact, scope-aware real-data snapshot the LLM answers from."""
        ops = self.frames.get("ops")
        home = self.home_unit_id(user)
        scope = self.scope_of(user)

        # monthly trend for the user's home aggregate
        series = []
        if ops is not None:
            hs = ops[ops.unit_id == home].sort_values("ym")
            series = [{"ym": r.ym, "vessel_calls": _cl(r.vessel_calls),
                       "cargo_mt": _cl(r.cargo_mt),
                       "avg_turnaround_hr": _cl(r.get("avg_turnaround_hr")),
                       "avg_waiting_hr": _cl(r.get("avg_waiting_hr"))}
                      for _, r in hs.iterrows()]

        # visible child units latest
        vis = self.visible(self.unit_latest, user)
        child = self.child_level(user)
        units = vis[vis.level == child] if len(vis) else vis
        ucols = ["unit_name", "terminal", "zone", "vessel_calls", "cargo_mt", "teu",
                 "avg_turnaround_hr", "avg_waiting_hr", "occupancy_pct",
                 "incidents_total", "detentions", "outstanding_cr"]
        units_latest = [{c: _cl(r[c]) for c in ucols if c in r.index} for _, r in units.iterrows()][:60]

        findings = [{"id": f["id"], "area": f["area"], "severity": f["severity"],
                     "title": f["title"], "inference": f.get("inference", ""),
                     "evidence": f.get("evidence", {})} for f in self.findings]

        return {
            "geography": "Mundra Port (INMUN), Kutch, Gujarat — India's largest commercial "
                         "port: port → 3 cargo zones → 10 terminals → 24 berths.",
            "your_scope": scope,
            "latest_month": self.latest_month,
            "coverage": "Portal operations data, monthly Jan 2023 – present; berth is the "
                        "finest grain. All transactions are the portal's fictional demo "
                        "world; benchmarks are public major-port statistics.",
            "metric_definitions": {
                "avg_turnaround_hr": "mean hours anchorage-arrival → sailing for calls "
                                     "completed in the month",
                "avg_waiting_hr": "mean hours at anchorage before berthing",
                "berthed_lt6h_pct": "share of calls berthed within 6h of arrival — the "
                                    "customer-facing service level",
                "occupancy_pct": "occupied berth-hours / available berth-hours",
                "avg_output_mt_per_berthday": "cargo tonnes handled per occupied berth-day",
                "detentions": "PSC/FSI detentions recorded in the month",
                "outstanding_cr": "cumulative billed minus collected, ₹ crore",
                "risk_score": "composite 0-100: incident rate 35 · waiting 25 · "
                              "high-severity incidents 25 · detentions 15 (trailing 12m)",
            },
            "major_port_benchmark": {k: _cl(v) for k, v in self.benchmark.items()},
            "home_series": series,
            "units_latest": units_latest,
            "findings": findings,
            "vessel_reliability": (self.frames["vessel_reliability"].head(12).to_dict("records")
                                   if "vessel_reliability" in self.frames else []),
            "vessel_watchlist_top": (
                self.frames["vessel_watchlist"].head(15).to_dict("records")
                if "vessel_watchlist" in self.frames else []),
            "fleet_and_crew": {
                "fleet": (self.sections.get("fleet", {}) or {}).get("kpis", {}),
                "crew": (self.sections.get("crew", {}) or {}).get("kpis", {}),
                "note": "the 8 documented liner callers carry clean records and are "
                        "excluded from the watchlist by design",
            },
        }


_store = None
_store_lock = threading.Lock()


def get_store():
    global _store
    if _store is None:
        with _store_lock:
            if _store is None:
                _store = Store()
    return _store
